using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Text;
using BepInEx;
using Entities;
using GameState.Data;

namespace ComboMod
{
    /// <summary>
    /// Value parsing and C# export for the in-game editor.
    /// <para>
    /// Kept out of <see cref="ModPanel"/> so the IMGUI code stays about layout, and so the
    /// export can be driven from the API without a panel open.
    /// </para>
    /// </summary>
    internal static class LiveEditor
    {
        /// <summary>
        /// Parse editor text into a knob's value type. Returns false on anything unparseable so
        /// the panel can keep showing the user's in-progress typing rather than snapping back.
        /// </summary>
        internal static bool TryParse(Tuner.Knob knob, string text, out object value)
        {
            value = null;
            if (knob == null || string.IsNullOrEmpty(text))
                return false;

            // Mid-typing states that are not yet numbers. Treat as "not ready", not an error.
            if (text == "-" || text == "." || text == "-.")
                return false;

            if (knob.Type == typeof(int))
            {
                if (int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out int i))
                {
                    value = i;
                    return true;
                }
                return false;
            }

            if (knob.Type == typeof(float))
            {
                if (float.TryParse(text, NumberStyles.Float, CultureInfo.InvariantCulture, out float f))
                {
                    value = f;
                    return true;
                }
                return false;
            }

            if (knob.Type == typeof(Rarity))
            {
                try
                {
                    value = (Rarity)Enum.Parse(typeof(Rarity), text, ignoreCase: true);
                    return true;
                }
                catch
                {
                    return false;
                }
            }

            return false;
        }

        /// <summary>Format a value the way the editor and the exporter both want to see it.</summary>
        internal static string Format(object value)
        {
            if (value == null)
                return string.Empty;

            if (value is float f)
                return f.ToString("0.####", CultureInfo.InvariantCulture);

            return Convert.ToString(value, CultureInfo.InvariantCulture);
        }

        /// <summary>
        /// Render the current live edits as a compilable C# source file, so a session of
        /// in-game tweaking can become a real mod without retyping numbers.
        /// </summary>
        internal static string BuildExport()
        {
            var sb = new StringBuilder();
            sb.AppendLine("// Generated by ComboMod's in-game editor.");
            sb.AppendLine("// Drop into a BepInPlugin's Awake() to make these edits permanent.");
            sb.AppendLine();

            foreach (KeyValuePair<GameTag, Dictionary<string, object>> entry in ComboModApi.Overrides)
            {
                if (entry.Value.Count == 0)
                    continue;

                sb.AppendLine("ComboModApi.Tune(GameTag." + entry.Key + ", t =>");
                sb.AppendLine("{");

                foreach (KeyValuePair<string, object> field in entry.Value)
                {
                    Tuner.Knob knob = Tuner.FindKnob(field.Key);
                    if (knob == null)
                        continue;

                    string literal;
                    if (knob.Type == typeof(float))
                        literal = Format(field.Value) + "f";
                    else if (knob.Type == typeof(Rarity))
                        literal = "Rarity." + field.Value;
                    else
                        literal = Format(field.Value);

                    sb.AppendLine("    t." + knob.Name + " = " + literal + ";");
                }

                sb.AppendLine("});");
                sb.AppendLine();
            }

            if (sb.Length == 0)
                sb.AppendLine("// No live edits to export.");

            return sb.ToString();
        }

        /// <summary>Write the export next to the config and return the path, or null on failure.</summary>
        internal static string WriteExport()
        {
            try
            {
                string path = Path.Combine(Paths.ConfigPath, "ComboMod.exported.cs");
                File.WriteAllText(path, BuildExport());
                ComboModApi.Log?.LogInfo("Exported live edits to " + path);
                return path;
            }
            catch (Exception ex)
            {
                ComboModApi.Log?.LogError("Export failed: " + ex);
                return null;
            }
        }
    }
}
